####################################
# Port & Project Name
####################################
server:
  port: 8080                    # 포트 설정
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: TodoBack
  config:
    import: "optional:classpath:application-db.yml"

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      preserve-session: true  # session

  ####################################
  # JPA
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  ####################################
  # Security User
  ####################################
  security:
    user:
      name: test@test.com
      password: 1111

  ####################################
  # File Size Limit
  ####################################
  servlet:
    multipart:
      max-file-size: 20MB         # 파일 업로드 최대 크기
      max-request-size: 20MB      # 파일 업로드 최대 크기

####################################
# File Upload
####################################
imgLocation: D:/upload/item/    # 서버 내부에서 이미지가 저장될 실제 디렉토리 경로(파일 저장 경로)
uploadPath: file:///D:/upload/      # 외부에서 이미지에 접근할 수 있는 URL 경로(파일 업로드 경로)

####################################
# Log
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

####################################
# Swagger
####################################
springdoc:
  swagger-ui:
    path: /api-test  # Swagger UI의 접속 경로를 설정. 기본적으로 http://localhost:8080/swagger-ui/index.html에서 접근 가능하지만, /api-test로 변경됨.
    groups-order: DESC # API 그룹 정렬 순서를 내림차순(DESC)으로 설정.
    tags-sorter: alpha # API 태그들을 알파벳 순서로 정렬.
    operations-sorter: method  # HTTP 메서드(delete - get - patch - post - put) 순서대로 정렬. "alpha"로 설정하면 알파벳 순으로 정렬됨.
  paths-to-match:
    - /** # Swagger UI에서 문서화할 API의 경로를 지정. 모든 API(`/**`)를 포함하도록 설정.

