####################################
# ?? ? ???? ?? ??
####################################
server:
  port: 8080                    # ?? ??
  servlet:
    encoding:
      charset: UTF-8          # ?? ??? ??
      force: true             # ?? ??

spring:
  application:
    name: TodoBack

  devtools:
    livereload:
      enabled: true           # ?? ??? ??
    restart:
      enabled: true           # ?? ??? ??
      preserve-session: true  # ?? ?? ??

  ####################################
  # ?????? ??
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_list?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  ####################################
  # JPA ??
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ????? ???? ??? ??
    show-sql: true          # SQL ?? ???
    properties:
      hibernate:
        format_sql: true    # ?? ???? ???
        default_batch_fetch_size: 1000  # ??? ??? ??? ? in ?? ?? ??

  ####################################
  # Security User
  ####################################
  security:
    user:
      name: test@test.com
      password: 1111

####################################
# ?? ?? ??
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # ???? ??? ???? ??

####################################
# Swagger ??
####################################
springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.

    groups-order: DESC # path, query, body, response ??? ??

    tags-sorter: alpha # ??? ??? ??? ??

    operations-sorter: method  # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??

  paths-to-match:
    - /** # swagger-ui? ??? api? ????? ??